parameters:
  - name: stageName
    default: ''
    type: string

  - name: stageDisplayName
    default: ''
    type: string  

  - name: namespace
    default: ''
    type: string  

  - name: buildReason
    default: 'IndividualCI'
    type: string 

  - name: isTargetBranch 
    default: true
    type: boolean

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  condition: and(always(), eq(variables['Build.Reason'], '${{ parameters.buildReason }}'), ${{ parameters.isTargetBranch }})
  jobs:
    - job: Test
      displayName: Test
      steps:
        - script: echo Maven Test

    - job: BuildAndDeploy
      displayName: Build & Depoly
      dependsOn: Test
      steps:
        - script: echo Build Image
        - script: echo Push Image
        - script: echo Deploy to ${{ parameters.namespace }}
        - script: echo RollBack
    
    - job: SendErrorNotification
      displayName: Send Error Notification
      dependsOn: Test
      condition: failed()
      steps:
        - script: echo Sending Notification to Development Team