parameters:
  # - name: stageName
  #   default: ""
  #   type: string

  # - name: stageDisplayName
  #   default: ''
  #   type: string

  # - name: namespace
  #   default: ''
  #   type: string

  # - name: buildReason
  #   default: "IndividualCI"
  #   type: string

  # - name: isTargetBranch
  #   default: true
  #   type: boolean
  - name: environment
    type: object
    default:
      env: "dev"
      stageName: "Dev"
      buildReason: "IndividualCI"

stages:
  - stage: ${{ parameters.environment.stageName }} and ${{ parameters.environment.isTargetBranch }}
    # displayName: ${{ variables.stageDisplayName }}
    condition: and(always(), eq(variables['Build.Reason'], '${{ parameters.environment.buildReason }}'))
    variables:
      - template: vars/vars-test.yml
    jobs:
      - job: test
        displayName: ${{ variables.namespace }}
        steps:
          - script: echo ${{ variables.namespace }}
  # - stage: ${{ variables.stageName }}
  #   displayName: ${{ variables.stageDisplayName }}
  #   condition: and(always(), eq(variables['Build.Reason'], '${{ variables.buildReason }}'), ${{ variables.isTargetBranch }})
  #   variables:
  #     - template: vars/vars-${{ parameters.environment }}.yml
  #   jobs:
  #     - job: Test
  #       displayName: Test
  #       steps:
  #         - script: exit 1

  #     - job: BuildAndDeploy
  #       displayName: Build & Depoly
  #       dependsOn: Test
  #       steps:
  #         - script: echo Build Image
  #         - script: echo Push Image
  #         - script: echo Deploy to ${{ variables.namespace }}
  #         - script: echo RollBack

  #     - job: SendErrorNotification
  #       displayName: Send Error Notification
  #       dependsOn: Test
  #       condition: failed()
  #       steps:
  #         - script: echo Sending Notification to Development Team
