parameters:
  - name: stageName
    default: ""
    type: string

  # - name: stageDisplayName
  #   default: ''
  #   type: string

  # - name: namespace
  #   default: ''
  #   type: string

  - name: buildReason
    default: ''
    type: string

  - name: dummy
    default: ''
    type: string

  - name: isTargetBranch
    default: true
    type: boolean

  - name: env
    type: string
    default: ''

    # default:
    #   env: "dev"
    #   stageName: "Dev"
    #   buildReason: "IndividualCI"

stages:
  - stage: sName_${{ parameters.stageName }}_isBranch_${{ eq(variables['Build.SourceBranch'], 'refs/heads/'parameters.env) }} ${{ parameters.isTargetBranch }}_reason_${{ parameters.buildReason }}_dummy_${{ parameters.dummy }}_env_${{ parameters.env }}
    # displayName: ${{ variables.stageDisplayName }}
    condition: and(always(), eq(variables['Build.Reason'], 'IndividualCI'))
    variables:
      - template: vars/vars-test.yml
    jobs:
      - job: test
        displayName: jName_${{ variables.stageName }}_ns_${{ variables.namespace }}_reason${{ variables.buildReason }}_isBranch_${{ variables.isTargetBranch }}
        steps:
          - script: echo ${{ variables.namespace }}
  # - stage: ${{ variables.stageName }}
  #   displayName: ${{ variables.stageDisplayName }}
  #   condition: and(always(), eq(variables['Build.Reason'], '${{ variables.buildReason }}'), ${{ variables.isTargetBranch }})
  #   variables:
  #     - template: vars/vars-${{ parameters.environment }}.yml
  #   jobs:
  #     - job: Test
  #       displayName: Test
  #       steps:
  #         - script: exit 1

  #     - job: BuildAndDeploy
  #       displayName: Build & Depoly
  #       dependsOn: Test
  #       steps:
  #         - script: echo Build Image
  #         - script: echo Push Image
  #         - script: echo Deploy to ${{ variables.namespace }}
  #         - script: echo RollBack

  #     - job: SendErrorNotification
  #       displayName: Send Error Notification
  #       dependsOn: Test
  #       condition: failed()
  #       steps:
  #         - script: echo Sending Notification to Development Team
